[package]
name = "ssq"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calamine = "0.22.1"
clap = { version = "4.4.6", features = ["derive"] }
colored = "2.0.4"
csv = "1.3.0"
